# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34930ed88bfd18e49c565e32207fe47524626323227f7828b25c031ffab149ae8a063d27f215098eb68c95118c3d1e4127fb1f17941c63f6ed407056411f3014

test:
  secret_key_base: 4f3f44f5a8ad1490811b2c0548e2cb2207b63b386e796a4198a2883eafcd7494f628de6e9697f2c3de430d5e7b890c9f0ac0ee6eda48375c6914d8bf1f73ba02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
